name: clustering
channels:
  - defaults
dependencies:
  - python=3.8
  - torchvision
  - pytorch
  - jupyter
  - pandas
  - scipy
  - numpy
  - scikit-learn
  - ipykernel
  - jupyterlab
  - openpyxl
  - nltk
  - psutil


